### ISSUE TITLE
Readme getting starting / usage section

### ISSUE THREAD

**Issue by dhimmel** [katlol/trackmyairtag#1]
I was [looking through](https://www.reddit.com/r/AirTags/comments/wroi8q/comment/jj593r0/) a bunch of repos for AirTag location history tracking and this one caught my eye! It is an honor to open the first issue.

I was generally curious about how to use this, e.g. what commands to run, whether any configuration is needed, etcetera. Did you have any initial advice, either here or as a usage section in the readme?

Also happy to contribute back any docs as I figure the package out.

**Comment by katlol** [comment]
hey. thank you for your interest! I think it is. I used to run the docker stack on a remote server, and then ran locally on the macbook:

```TMA_DATABASE_DSN=postgres://...:5432/trackmyairtag adev runserver app.py```

**Comment by dhimmel** [comment]
Thanks @katlol. Nice design that you can easily run the docker stack on a server.

Am figuring things out locally now on a mac with FindMy running. After changing the user in:

https://github.com/katlol/trackmyairtag/blob/533d603eff3c46842c3ba12000a40ad46e0cfb09/docker-compose.yaml#L8

`docker compose up` launches properly.

However, I'm hitting:

```
web_1       |   File "asyncpg/protocol/protocol.pyx", line 168, in prepare
web_1       | asyncpg.exceptions.UndefinedTableError: relation "log" does not exist
postgres_1  | 2023-05-10 14:07:01.165 UTC [30] ERROR:  relation "log" does not exist at character 368
postgres_1  | 2023-05-10 14:07:01.165 UTC [30] STATEMENT:  
postgres_1  | 	                SELECT
postgres_1  | 	                    id,
postgres_1  | 	                    name,
postgres_1  | 	                    address,
postgres_1  | 	                    timestamp,
postgres_1  | 	                    latitude,
postgres_1  | 	                    longitude,
postgres_1  | 	                    altitude,
postgres_1  | 	                    raw->'location'->'horizontalAccuracy' as accuracy,
postgres_1  | 	                    raw->'role'->'emoji' as emoji
postgres_1  | 	                FROM log
postgres_1  | 	                WHERE
postgres_1  | 	                    log.timestamp IN (SELECT max(timestamp) FROM log AS b WHERE log.id = b.id)
```

Perhaps [`_initdb`](https://github.com/katlol/trackmyairtag/blob/533d603eff3c46842c3ba12000a40ad46e0cfb09/utils/db.py#L84C15-L102) hasn't run yet. Should that happen automatically or does the user need to trigger it?

**Comment by katlol** [comment]
yeah, you are right. that does not seem to be called anywhere.

perhaps we want to wrap it in a try/except (in case it runs for the second time?) or make it idempotent (it might already be?)

**Comment by dhimmel** [comment]
> make it idempotent (it might already be?)

Okay included as part of https://github.com/katlol/trackmyairtag/pull/3. I believe `_initdb` works fine when called on an existing databse.

**Comment by katlol** [comment]
@dhimmel see #4 maybe related?

**Comment by katlol** [comment]
@dhimmel please reopen if this is still an issue.
